language: node_js 
sudo: required

node_js:
  - "5"
  - "4"
  - "0.12"

addons:
 apt:
  packages:
   - curl
   - git 
   - make 
   - unzip 
   - apache2 
   - pandoc

script:
 - PHANTOMJS_TIMEOUT=45 make check

