language: javascript 
sudo: required
matrix:
  include:
#    - os: linux
#      dist: trusty
#      compiler: clang
#      env:
#       - MY_OS=trusty
#    - os: linux
#      dist: precise
#      compiler: gcc
#      env:
#       - MY_OS=precise
    - os: osx
      env:
       - MY_OS=macos
addons:
 apt:
  packages:
   - curl
   - git 
   - make 
   - unzip 
   - apache2 
   - pandoc

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pandoc; fi

before_script:
 - true
script:
 - PHANTOMJS_TIMEOUT=40 make check
