language: javascript 
sudo: required
matrix:
  include:
    - os: linux
      dist: trusty
      compiler: clang
      env:
       - MY_OS=trusty
    - os: linux
      dist: precise
      compiler: gcc
      env:
       - MY_OS=precise
#    - os: osx
#      osx_image: xcode7.2
#      env:
#       - MY_OS=macos
addons:
 apt:
  packages:
   - curl
   - git 
   - make 
   - unzip 
   - apache2 
   - pandoc

before_install:
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pkg-config icu4c yaz; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./test/travis/travis-init.sh; fi

before_script:
 - true
script:
 - make check
